// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9C2EhBFaEWcudJGcF8mHzJpVttf9MpCY',
    appId: '1:76673791229:web:44342bd915d3b49a34fa94',
    messagingSenderId: '76673791229',
    projectId: 'paonde-app',
    authDomain: 'paonde-app.firebaseapp.com',
    storageBucket: 'paonde-app.firebasestorage.app',
    measurementId: 'G-G4TD8N1F9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqhhCc8ZZF5L6Srjre6JzkgEswd4Ps2I',
    appId: '1:76673791229:android:44b14a22b5fe978134fa94',
    messagingSenderId: '76673791229',
    projectId: 'paonde-app',
    storageBucket: 'paonde-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC03vbeBcGnq2ltTKRsmcvcJgu-zJyLfWY',
    appId: '1:76673791229:ios:bd4ceb9da1f4bfd234fa94',
    messagingSenderId: '76673791229',
    projectId: 'paonde-app',
    storageBucket: 'paonde-app.firebasestorage.app',
    iosBundleId: 'com.example.paondeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC03vbeBcGnq2ltTKRsmcvcJgu-zJyLfWY',
    appId: '1:76673791229:ios:bd4ceb9da1f4bfd234fa94',
    messagingSenderId: '76673791229',
    projectId: 'paonde-app',
    storageBucket: 'paonde-app.firebasestorage.app',
    iosBundleId: 'com.example.paondeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9C2EhBFaEWcudJGcF8mHzJpVttf9MpCY',
    appId: '1:76673791229:web:7b1d19ac7c177b6334fa94',
    messagingSenderId: '76673791229',
    projectId: 'paonde-app',
    authDomain: 'paonde-app.firebaseapp.com',
    storageBucket: 'paonde-app.firebasestorage.app',
    measurementId: 'G-0R2QGSL3CD',
  );
}
